spring:
  application:
    name: exam
  datasource:
    url: jdbc:mysql://localhost:3306/exam_mgt?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 246800
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: w9Fb6pX2zL3hA7yR5tK8vQ1mN4jU7iZ0cV9xG3dS5fH2eB4nJ6
  expiration: 86400000

file:
  upload:
    path: C:/Users/33912/Desktop/paper/exam/uploads
    access-path: /api/uploads 